### ISSUE TITLE
Compilation of npm package's `dist/index.js` and compatibility with Jest

### ISSUE THREAD

**Issue by andrew-breunig** [mrcrowl/vuex-typex#6]
I've run into syntax errors when running Jest tests with Vue.js, Vuex, TypeScript, and `vuex-typex`. I'm fairly new to working with Vue.js, TypeScript, and Jest.

It may be useful to mention that the tests in question are written directly against a Vuex store object, not a Vue component.

Here's the error output I get:

```
Test suite failed to run

    .../node_modules/vuex-typex/dist/index.js:19
    import { Store } from "vuex";
    ^^^^^^

    SyntaxError: Unexpected token import

      at ScriptTransformer._transformAndBuildScript (node_modules/jest-runtime/build/script_transformer.js:305:17)
      at Object.<anonymous> (src/store/main.ts:9:18)
      ...
```

I'm using the following versions of these tools:

- `"vue": "^2.5.10"`
- `"vuex": "^3.0.0"`
- `"typescript": "^2.6.2"`
- `"vuex-typex": "^3.0.1"`
- `"jest": "^21.2.1"`
- `"jest-vue-preprocessor": "^1.3.1"`
- `"@types/jest": "^21.1.8"`
- `"ts-jest": "^21.2.4"`
- `"typescript-babel-jest": "^1.0.5"`

And here are the configuration settings that process test code:

`.babelrc`
```
{
  "presets": [
    ["env", {
      "modules": false,
      "targets": {
        "browsers": ["> 1%", "last 2 versions", "not ie <= 8"]
      }
    }],
    "stage-2"
  ],
  "plugins": ["transform-runtime"],
  "env": {
    "test": {
      "presets": ["env", "stage-2"]
    }
  }
}
```

`package.json`
```
...
"jest": {
    "moduleFileExtensions": [
      "js",
      "ts",
      "vue"
    ],
    "moduleNameMapper": {
      "^@/(.*)$": "<rootDir>/src/$1",
      "\\.(jpg|jpeg|png|gif|eot|otf|webp|svg|ttf|woff|woff2|mp4|webm|wav|mp3|m4a|aac|oga)$": "<rootDir>/mocks/file.ts",
      "\\.(css|less)$": "<rootDir>/mocks/style.ts"
    },
    "transform": {
      ".*\\.(vue)$": "<rootDir>/node_modules/jest-vue-preprocessor",
      ".(ts|tsx)": "<rootDir>/node_modules/ts-jest/preprocessor.js",
      ".*": "<rootDir>/node_modules/babel-jest"
    },
    "transformIgnorePatterns": [
      "<rootDir>/node_modules/(?!vuex-i18n).+\\.js$"
    ],
    "testMatch": [
      "**/?(*.)spec.ts"
    ],
    "verbose": true
  }
...
```

`tsconfig.json`
```
...
"jest": {
    "globals": {
      "ts-jest": {
        "compilerOptions": {
          "module": "commonjs"
        },
        "include": [
          "./test/**/*"
        ]
      }
    }
  }
...
```

I thought this might be some kind of compilation issue in the distribution code published to npm, so I tried manually processing the `dist/index.js` file with [Babel](https://babeljs.io/repl/) to the targets I'm using:

- `es2015`
- `stage-2`
- `"browserslist": [
    "> 1%",
    "last 2 versions",
    "not ie <= 8"
  ]`

This appeared to resolve the issue for me, but I'm only partially confident in my diagnosis. I don't see any other issues (open or closed) on this repository that would suggest others have run into this problem. I don't want to apply a misguided workaround or obscure an underlying implementation problem in my code.

I'm hoping that this is just a simple oversight or misunderstanding on my part. Can you offer any insight? Have you, or others you know, used this particular set of tools together with Jest tests? It appears that the tests for `vuex-typex` were written with Mocha and Chai, but I imagine that others must be using this with Jest, too.

**Comment by hartmut-co-uk** [comment]
Same issue here but with **SSR**, not with Jest - can't get it working via babel though as mentioned.

**Comment by zelid** [comment]
The same issue with SSR

**Comment by ChristopherKiss** [comment]
I'm having this same issue with mocha and chai and not using SSR. I'm using the vue-cli 3.0 generator for the typescript starter.

I don't know how to fix this, does anyone have a solution. I'm including my info below in case it helps anyone.

```
D:\Development\***\node_modules\vuex-typex\dist\index.js:19import { Store } from "vuex";
^^^^^^

SyntaxError: Unexpected token import
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Module._extensions..js (module.js:663:10)
    at Object._module2.default._extensions.(anonymous function)
```

`package.json`
```
 "dependencies": {
        "bulma": "^0.6.2",
        "lodash": "^4.17.5",
        "typeface-roboto": "0.0.54",
        "vue": "^2.5.13",
        "vue-class-component": "^6.0.0",
        "vue-property-decorator": "^6.0.0",
        "vue-router": "^3.0.1",
        "vuex": "^3.0.1",
        "vuex-persist": "^1.1.5",
        "vuex-typex": "^3.0.1"
    },
    "devDependencies": {
        "@types/chai": "^4.1.0",
        "@types/lodash": "^4.14.106",
        "@types/mocha": "^2.2.46",
        "@vue/cli-plugin-babel": "^3.0.0-beta.6",
        "@vue/cli-plugin-eslint": "^3.0.0-beta.6",
        "@vue/cli-plugin-typescript": "^3.0.0-beta.6",
        "@vue/cli-plugin-unit-mocha": "^3.0.0-beta.6",
        "@vue/cli-service": "^3.0.0-beta.6",
        "@vue/eslint-config-airbnb": "^3.0.0-beta.6",
        "@vue/eslint-config-typescript": "^3.0.0-beta.6",
        "@vue/test-utils": "^1.0.0-beta.10",
        "chai": "^4.1.2",
        "node-sass": "^4.7.2",
        "sass-loader": "^6.0.6",
        "vue-template-compiler": "^2.5.13"
    },
    "babel": {
        "presets": [
            "@vue/app"
        ]
    },
    "eslintConfig": {
        "root": true,
        "extends": [
            "plugin:vue/essential",
            "@vue/airbnb",
            "@vue/typescript"
        ]
    },
    "postcss": {
        "plugins": {
            "autoprefixer": {}
        }
    },
    "browserslist": [
        "> 1%",
        "last 2 versions",
        "not ie <= 10"
    ]
```

`main.ts`
```
import Vue from 'vue';
import store from './store/store';
import app from './app.vue';
import router from './router';

Vue.config.productionTip = false;

new Vue({
    store,
    router,
    render: h => h(app),
}).$mount('#app');
```

`store.ts`
```
import Vue from 'vue';
import Vuex, { Store, StoreOptions } from 'vuex';
import VuexPersist from 'vuex-persist';
import { IRootState } from '@/typings/store.d';
import { getStoreBuilder } from 'vuex-typex';
import './modules/player';

Vue.use(Vuex);

const debug = process.env.NODE_ENV !== 'production';
const test = process.env.NODE_ENV === 'test';

const storeOptions: StoreOptions<IRootState> = {
    strict: debug
};

if (!test) {
    const vuexLocalStorage = new VuexPersist({
        key: 'vuex',
        strictMode: debug,
        storage: window.localStorage
    });

    storeOptions.mutations = {
        RESTORE_MUTATION: vuexLocalStorage.RESTORE_MUTATION
    };

    storeOptions.plugins = [vuexLocalStorage.plugin];
}

const store: Store<IRootState> = getStoreBuilder<IRootState>().vuexStore(storeOptions);
export default store;
```

`player.ts`
```
import { IRootState, IPlayerState } from '@/typings/store.d';
import { getStoreBuilder, BareActionContext } from 'vuex-typex';

const initialState: IPlayerState = {
    isSetup: false,
    name: 'Player',
    totalExperience: 1
};

const builder = getStoreBuilder<IRootState>().module<IPlayerState>('player', initialState);
const stateGetter = builder.state();

// Helpers.
function getExperienceForLevel(level: number) {
    return level ** 3;
}

// Getters.
const levelGetter = builder.read(state => Math.min(100, Math.floor(Math.cbrt(state.totalExperience))), 'level');

const levelExperienceGetter = builder.read(state => getExperienceForLevel(player.level + 1) - getExperienceForLevel(player.level), 'levelExperience');

const currentLevelExperienceGetter = builder.read(state => state.totalExperience - getExperienceForLevel(player.level), 'currentLevelExperience');

const experienceToLevelGetter = builder.read(state => player.levelExperience - player.currentLevelExperience, 'experienceToLevel');

// Mutations.
function commitSetName(state: IPlayerState, name: string) {
    state.name = name;
}

function commitAddExperience(state: IPlayerState, experience: number) {
    state.totalExperience += experience;
}

const mutations = {
    commitSetName: builder.commit(commitSetName),
    commitAddExperience: builder.commit(commitAddExperience),
};

// Actions.
function setName(context: BareActionContext<IPlayerState, IRootState>, name: string) {
    mutations.commitSetName(name);
}

function addExperience(context: BareActionContext<IPlayerState, IRootState>, experience: number) {
    mutations.commitAddExperience(experience);
}

const player = {
    get state() { return stateGetter(); },

    get level() { return levelGetter(); },
    get levelExperience() { return levelExperienceGetter(); },
    get currentLevelExperience() { return currentLevelExperienceGetter(); },
    get experienceToLevel() { return experienceToLevelGetter(); },

    setName: builder.dispatch(setName),
    addExperience: builder.dispatch(addExperience)
};

export default player;
```

`player.spec.ts`
```
import { expect } from 'chai';
import player from '@/store/modules/player';

describe('player', () => {
    it('is defined', () => {
        expect(player).to.be.not.undefined;
    });
});
```

**Comment by mrcrowl** [comment]
This _should_ be addressed by more recent builds. Please reopen if this is still occurring.
